### ISSUE TITLE
[Bug] Can't click and drag a request into an empty folder

### ISSUE THREAD

**Issue by robclancy** [Kong/insomnia#1486]
- Insomnia Version: 6.5.1
- Operating System: Arch Linux

## Details

Created a new folder and attempted to move a request into it and it would just do it below the new folder. I created an empty request in the folder and then moving into it would work. I think this is a new issue to 6.5.

**Comment by robclancy** [comment]
Calm down I only just reported it :open_mouth:

**Comment by gschier** [comment]
Hehe, it was an easy fix! 😄 

Thanks for taking the time to report it 💯

**Comment by hawkeng** [comment]
Looks like the fix was reverted. Drag & Drop still not working on version 7.0.6

**Comment by rusterholz** [comment]
@gschier As of Insomnia v7.1.1 on macOS 10.14.5 this appears to not be fixed. I'm seeing the exact behavior originally described by @robclancy.

**Comment by alecglen** [comment]
^ Same on Ubuntu 20.04 with Insomnia 2020.3.3

**Comment by nugmanoff** [comment]
Same thing on macOS 10.15.5, Insomnia Version 2020.3.3

**Comment by develohpanda** [comment]
Reopening as per above reports

**Comment by develohpanda** [comment]
Hi @alecglen @nugmanoff, could you please add any screenshots or a screen recording to show what you are seeing? When I drag a request into the empty folder, I see the dotted line indicating the request will be placed inside the folder, which works successfully.

![](http://g.recordit.co/PLHhtbhMzV.gif)

**Comment by PenguinShade** [comment]
I'm on version 2020.4.2
I'm also experiencing whenever I try to drag and drop it doesn't do anything.
![insomnia-drag-bug](https://user-images.githubusercontent.com/16569829/99853839-94d3bf00-2b38-11eb-8924-bc4e1da2538d.gif)

**Comment by develohpanda** [comment]
@PenguinShade is that still the case after you restart the application?

Your report (and possibly the extra reports above) are unrelated to dragging _into a folder_ (this issue), but related to _dragging_ in general (new issue). It looks like you can't even grab a request as per your gif. What OS are you on?

**Comment by PenguinShade** [comment]
@develohpanda I'm on Ubuntu 20.04.1
I started up the app again and now dragging works fine 😆
I think I was experiencing the bug on my first time opening the app after install. Maybe there is a bug with dragging upon first opening the app.

**Comment by firatesmer** [comment]
@PenguinShade 
I had the same issue. It wasn't the first time opening but after creating the folder, I had to restart my application and now issue is solved.

Windows Version: 20H2 (OS Build 19042.804)
Insomnia Version: Insomnia Core 2020.5.2

**Comment by SergiyKolesnikov** [comment]
I had a problem with dragging a request into a folder similar to this https://github.com/Kong/insomnia/issues/1486#issuecomment-731428913
But in my case I was not able to drag the top of two requests. I was able to drag the second request as expected. This happened on the first start of the app.

**Comment by rodrigoddc** [comment]
Same issue here. Can't move a request into an empty folder. 

OS: 20.04.1-Ubuntu
Insomnia: 2021.4.1

Creating any new request to the empty folder, I'm able to drag and drop the outer request into it

**Comment by mhewedy** [comment]
First thanks on this amazing software .... I like it alot ... easy to use yet simple.


I'd like to report the same issue here.

Version: Insomnia 2021.4.1
Release date: 7/7/2021
OS: Darwin x64 20.5.0
Electron: 9.3.5
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.42.0

**Comment by ghandmann** [comment]
I experienced the same issue. But i observed two things:

1) When i started Insomnia, it was updating itself. Then i created some request. And afterwards a folder. I could not drag and drop anything. But a newly created request inside the new folder was draggable.

2) After restarting drag and drop worked for all items.

Version: 2021.5.3
Running as a snap on Ubuntu 20.10.

**Comment by PenguinShade** [comment]
> @develohpanda I'm on Ubuntu 20.04.1 I started up the app again and now dragging works fine laughing I think I was experiencing the bug on my first time opening the app after install. Maybe there is a bug with dragging upon first opening the app.

I actually just encountered the same bug again, so can confirm it's not because of it being my first install of the app. Restarting fixed the problem again.

**Comment by keevitaja** [comment]
had the same issue, after restarting the app, moving started working again. app had been running days...

**Comment by amardeepkhera** [comment]
Seeing same issue on mac 2022.2.1
![Screen Shot 2022-04-04 at 7 56 45 pm](https://user-images.githubusercontent.com/5568424/161520600-0b6570d8-2449-47f4-9a6f-676c38d997f8.png)

**Comment by laszlotuss** [comment]
I still had this issue today in the latest Insomnia with macOS Monterey on M1 Pro.
<img width="400" alt="Képernyőfotó 2022-05-14 - 21 34 02" src="https://user-images.githubusercontent.com/2952613/168445920-6f8bcbb5-5809-4316-b870-6249347934d9.png">
But restarting Insomnia fixed the issue for me.

**Comment by wongstein** [comment]
I'm going to close this issue for now, since it seems that restarting the app fixes the issue (sometimes computers / programs need to be restarted).  Please feel free to re-open again if restarting doesn't fix the issue.

**Comment by rezekdan** [comment]
i don't think this issue is resolved yet. Restarting also does not help:

Version: Insomnia 2022.5.1
Build date: 17.8.2022
OS: Linux x64 5.4.0-125-generic
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64

**Comment by georgmittendorfer** [comment]
Version: Insomnia 2022.5.1
Build date: 8/17/2022
OS: Linux x64 5.19.0-1-amd64
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64

Same here (on Debian testing). Restart doesn't help.

**Comment by Jaffex** [comment]
Have this problem on:

Version: Insomnia 2022.6.0
Build date: 26.9.2022
OS: Linux x64 6.0.5-200.fc36.x86_64
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64

On Fedora 36 (Installed via provided rpm):
![Peek 2022-11-09 15-56](https://user-images.githubusercontent.com/31133207/200863874-48ab2935-8692-4598-ba70-dbf6214918f1.gif)

Edit: Restarting the application does not help.

**Comment by yesthesoup** [comment]
Also have this, restarting did not help.

Version: Insomnia 2022.6.0
Build date: 9/26/2022
OS: Darwin x64 21.5.0
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64

I was able to solve by clicking "Click to add first request..." in the empty folder, then dragging the one I wanted onto that new request to add it into the folder. Then I delete the dummy request.

Note this only seems to occur for the first folder in a workspace, the second one didn't have this problem.

**Comment by RawMajkel** [comment]
The problem still exists, also it would be nice if we could select more than one request and move all of them to a folder.

Version: Insomnia 2022.7.5
Build date: 19.01.2023
OS: Windows NT x64 10.0.22621
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

**Comment by akbortoli** [comment]
Same for me, problem still exist.

<img width="372" alt="Screen Shot 2023-03-02 at 5 17 14 am" src="https://user-images.githubusercontent.com/642163/222370964-f5941597-635c-4608-9308-bed7f4b6a2dc.png">

https://user-images.githubusercontent.com/642163/222371275-b45670a6-aa2f-47c7-94b3-584c53c655e4.mov

**Comment by praagyajoshi** [comment]
Same, the issue exists for me as well.

```
Version: Insomnia 2022.7.5
Build date: 1/19/2023
OS: Darwin arm64 22.3.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64
```

**Comment by crakage** [comment]
Same issue: 
`Version: Insomnia 2023.1.0
Build date: 3/9/2023
OS: Darwin x64 22.3.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64`

**Comment by mkonikov** [comment]
I've resorted to creating two dummy requests in the new folder, and then dragging my actual request between the two dummy ones. That's the only way I've gotten it to work.

**Comment by abaga129** [comment]
@mkonikov that work around worked for me as well. Thanks for sharing.

**Comment by tit1** [comment]
@mkonikov thanks, have to do the same. 

System Info:
Version: Insomnia 2023.1.0
Build date: 3/9/2023
OS: Darwin arm64 22.4.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64

**Comment by bverkron** [comment]
Loving Insomnia so far but was socked to run into this issue and then discover the bug report has been open for 4 years 😲.

Version: Insomnia 2023.1.0
Build date: 3/9/2023
OS: Darwin x64 20.6.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

**Comment by tsheaff** [comment]
This issue is NOT resolved. For me it doesn't help to restart Insomnia, doesn't help to click "Click to add first request...", and doesn't help to add other requests. I can drag requests into other folders, but the new folders seem persistently in a state of not being able to drag things into them

**Comment by rangicus** [comment]
Ditto, still cannot add requests to folders.

Version: Insomnia 2023.1.0
Build date: 3/9/2023
OS: Windows_NT x64 10.0.22621
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

**Comment by davehouser1** [comment]
So I can add requests into a folder, only if the folder is a main parent folder. 
However If I create a sub folder, then I **cannot** move requests into the sub folder. 

- Tried dragging and dropping or looking for some setting that I was missing. 
- Tried restarting host, and application.
- Tried selecting "Create first request"

Work around:
This is hardly a workaround, but the only solution was to rebuild my requests in side of the folder manually. Please fix this problem. 

Version: Insomnia 2023.2.0
Build date: 4/26/2023
OS: Windows_NT x64 10.0.17763
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

**Comment by exotexot** [comment]
Same issue. Super annoying...

Insomnia 2023.2.0
macOS (INTEL) 13.3.1

**Comment by akbortoli** [comment]
Same issue.

Version: Insomnia 2023.2.0
Build date: 4/26/2023
OS: Darwin arm64 21.6.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64
macOS (Apple M1 Pro) 12.6.3

**Comment by Maritims** [comment]
Same issue.

Version: Insomnia 2023.2.2
Build date: 17.5.2023
OS: Linux x64 6.3.7-arch1-1
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

**Comment by TheDevMinerTV** [comment]
Same issue here.

```
Version: Insomnia 2023.2.2
Build date: 5/17/2023
OS: Windows_NT x64 10.0.19045
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64
```

**Comment by Luifr** [comment]
Same issue.

Version: Insomnia 2023.4.0
Build date: 04/07/2023
OS: Windows_NT x64 10.0.22621
Electron: 23.3.9
Node: 18.12.1
V8: 11.0.226.20-electron.0
Architecture: x64

**Comment by JeanCharlesss** [comment]
I was also having this problem, but I noticed that I was doing it wrong, follow the steps:

**1 -** You must **open** the folder first;
**2 -** drag the request on top of the space that will open below, until a **purple dotted line** appears;

See as i did [here](https://prnt.sc/Qf2b9JUWPXL5)

My mistake was to try to put the request in the folder with the folder closed and on top of the folder and not in the space indicated

**Comment by Maritims** [comment]
> I was also having this problem, but I noticed that I was doing it wrong, follow the steps:
> 
> **1 -** You must **open** the folder first; **2 -** drag the request on top of the space that will open below, until a **purple dotted line** appears;
> 
> See as i did [here](https://prnt.sc/Qf2b9JUWPXL5)
> 
> My mistake was to try to put the request in the folder with the folder closed and on top of the folder and not in the space indicated

Considering the number of reports in this thread, I would say that method is not sufficiently intuitive.

**Comment by JeanCharlesss** [comment]
i understand, If so, everywhere I saw how they were dragging, were they doing it wrong, counterintuitive?

**Comment by Maritims** [comment]
> i understand, If so, everywhere I saw how they were dragging, were they doing it wrong, counterintuitive?
> 

@akbortoli showed a video a while ago of the behaviour I would expect to work. It is very typical of user interfaces of various kinds to allow dropping a resource on a folder to place the resource within that folder. This is what Insomnia should support. Try any file explorer for instance. Users are quite used to this.

**Comment by robclancy** [comment]
It's clear they are ignoring this issue. Someone should make a new one with the new information discussed above.

**Comment by Maritims** [comment]
> It's clear they are ignoring this issue. Someone should make a new one with the new information discussed above.

A new issue has been created here: https://github.com/Kong/insomnia/issues/5985

**Comment by barseghyanartur** [comment]
Dragging doesn't work for me as well.

```
Version: Insomnia 2022.5.1
Build date: 2022-8-17
OS: Linux x64 6.4.4-200.fc38.x86_64
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64
```

**Comment by lukepighetti** [comment]
Also having this issue

**Comment by MarkCay** [comment]
Still experiencing this issue.

**Comment by KristianFilo** [comment]
Same here. I can drag the requests around, but I can't move it from root to a folder. Sometimes it works, but it is completely random and I don't see any pattern.

https://github.com/Kong/insomnia/assets/18458128/52ed46ab-30c9-411a-933f-b35097edc520

**Comment by FredNeves95** [comment]
Same problem here, Kristian

**Comment by JMetcalfeBrightCloudGroup** [comment]
Same issue.
I'm unable to move file or folders

**Comment by seshan-kavisanka** [comment]
Same issue.

**Comment by juanchaur** [comment]
Same issue.


```
Version: Insomnia 2023.5.5
Build date: 8/18/2023
OS: Darwin x64 22.5.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

```

**Comment by travisneids** [comment]
I found the pattern - it is actually updating. If you move a Request into a folder, the UI does not update but if you visit another project then come back, it will display correctly; the Request will be in the folder.

Decent workaround for now.

**Comment by GPrimola** [comment]
Same thing...

```
Version: Insomnia 2023.5.5
Build date: 8/18/2023
OS: Darwin arm64 22.6.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: arm64
```

**Comment by exotexot** [comment]
Fixed in latest version.
Thanks!
